#Save and load data

##Set environment

In [2]:
#Connect to google drive

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
#change path

%cd '/content/drive/My Drive/Colab Notebooks/pandas_platzi'
!ls

/content/drive/My Drive/Colab Notebooks/pandas_platzi
1_first_steps.ipynb  2_dataframes.ipynb  3_save_and_load.ipynb

In [11]:
#Create a directory

!mkdir /content/drive/My\ Drive/Colab\ Notebooks/pandas_platzi/db

In [12]:
#Hack for new files in db directory

dir_pandas = '/content/drive/My Drive/Colab Notebooks/pandas_platzi/db/{}'.format('test.csv')

##Save data

In [14]:
import pandas as pd
import numpy as np
pd.__version__

'1.1.5'

In [16]:
#Create dict and convert to dataframe

dict_data = {
    'edad': [10,9,13,14,12,11,12],
    'cm': [115,110,130,155,125,120,125],
    'pais':['co','mx','co','mx','mx','ch','ch'],
    'genero':['M','F','F','M','M','M','F'],
    'Q1':[5,10,8,np.nan,7,8,3],
    'Q2':[7,9,9,8,8,8,9]
}

df = pd.DataFrame(dict_data)
df

   edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  110   mx      F  10.0   9
2    13  130   co      F   8.0   9
3    14  155   mx      M   NaN   8
4    12  125   mx      M   7.0   8
5    11  120   ch      M   8.0   8
6    12  125   ch      F   3.0   9

In [17]:
#Create file for storing data

dir_pandas = '/content/drive/My Drive/Colab Notebooks/pandas_platzi/db/{}'.format('test.csv')

In [18]:
#Save df in csv file
df.to_csv(dir_pandas)

In [20]:
#Check files in the directory

!ls /content/drive/My\ Drive/Colab\ Notebooks/pandas_platzi/db

test.csv

In [21]:
#Save df in csv file without index
df.to_csv(dir_pandas, index=False)

In [24]:
#Save df in excel file

dir_pandas = '/content/drive/My Drive/Colab Notebooks/pandas_platzi/db/{}'
df.to_excel(dir_pandas.format('test.xlsx'))

#Add index=False for removing index column

In [29]:
#Save json file

dir_pandas = '/content/drive/My Drive/Colab Notebooks/pandas_platzi/db/{}'
df.to_json(dir_pandas.format('test.json'))

#Add index=False for removing index column

In [36]:
#Save pickle file

dir_pandas = '/content/drive/My Drive/Colab Notebooks/pandas_platzi/db/{}'
df.to_pickle(dir_pandas.format('test.pkl'))

#Add index=False for removing index column

In [38]:
#Save parquet file

dir_pandas = '/content/drive/My Drive/Colab Notebooks/pandas_platzi/db/{}'
df.to_parquet(dir_pandas.format('test.parquet'))

#Add index=False for removing index column

##Read data

In [23]:
df_read = pd.read_csv('/content/drive/My Drive/Colab Notebooks/pandas_platzi/db/test.csv')
df_read

   edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  110   mx      F  10.0   9
2    13  130   co      F   8.0   9
3    14  155   mx      M   NaN   8
4    12  125   mx      M   7.0   8
5    11  120   ch      M   8.0   8
6    12  125   ch      F   3.0   9

In [25]:
#read data with different separator

#df_read = pd.read_csv('/content/drive/My Drive/Colab Notebooks/pandas_platzi/db/test.csv', sep='|')

In [26]:
#Read excel data

df_read = pd.read_excel('/content/drive/My Drive/Colab Notebooks/pandas_platzi/db/test.xlsx')
df_read

   Unnamed: 0  edad   cm pais genero    Q1  Q2
0           0    10  115   co      M   5.0   7
1           1     9  110   mx      F  10.0   9
2           2    13  130   co      F   8.0   9
3           3    14  155   mx      M   NaN   8
4           4    12  125   mx      M   7.0   8
5           5    11  120   ch      M   8.0   8
6           6    12  125   ch      F   3.0   9

In [33]:
#Read json file

df_read = pd.read_json('/content/drive/My Drive/Colab Notebooks/pandas_platzi/db/test.json')
df_read

   edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  110   mx      F  10.0   9
2    13  130   co      F   8.0   9
3    14  155   mx      M   NaN   8
4    12  125   mx      M   7.0   8
5    11  120   ch      M   8.0   8
6    12  125   ch      F   3.0   9

In [37]:
#Read pickle file

df_read = pd.read_pickle('/content/drive/My Drive/Colab Notebooks/pandas_platzi/db/test.pkl')
df_read

   edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  110   mx      F  10.0   9
2    13  130   co      F   8.0   9
3    14  155   mx      M   NaN   8
4    12  125   mx      M   7.0   8
5    11  120   ch      M   8.0   8
6    12  125   ch      F   3.0   9

In [39]:
#Read parquet file

df_read = pd.read_parquet('/content/drive/My Drive/Colab Notebooks/pandas_platzi/db/test.parquet')
df_read

   edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  110   mx      F  10.0   9
2    13  130   co      F   8.0   9
3    14  155   mx      M   NaN   8
4    12  125   mx      M   7.0   8
5    11  120   ch      M   8.0   8
6    12  125   ch      F   3.0   9